name: board_command_service
publish_to: none
resolution: workspace
version: 0.1.0
environment:
  sdk: ^3.13.0
dependencies:
  board_backend_api:
    path: ../../packages/backend_api
  board_game_contracts:
    path: ../../packages/game_contracts
  board_game_core:
    path: ../../packages/game_core
  crypto: 3.0.7
  dart_jsonwebtoken: 3.4.1
dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
