import 'dart:convert';
import 'dart:io';

import 'package:board_command_service/command_service.dart';
import 'package:board_game_core/game_core.dart';
import 'package:test/test.dart';

import 'support/synthetic_tax_free_parking_fixture.dart';
import 'support/synthetic_tax_free_parking_plans.dart';

void main() {
  final catalog = syntheticTaxFreeParkingCatalog();

  AuthorityTaxFreeParkingEvaluation evaluate({
    required PublicGameState state,
    String operationId = 'landing-1',
    int expectedStateVersion = 1,
    int? expectedLandingIndex,
  }) => AuthorityTaxFreeParkingPlanner.evaluateSystem(
    operationId: operationId,
    expectedStateVersion: expectedStateVersion,
    playerId: 'p1',
    expectedLandingIndex:
        expectedLandingIndex ??
        state.players.singleWhere((player) => player.playerId == 'p1').position,
    state: state,
    catalog: catalog,
    transitionTime: syntheticTaxFreeParkingTime,
  );

  test('configured tax exposes one safe atomic Authority plan', () {
    final source = syntheticTaxFreeParkingState();
    final accepted = evaluate(state: source) as AuthorityTaxFreeParkingAccepted;

    expect(accepted.plan.enginePlan.kind, LandingEconomyKind.taxPaid);
    expect(accepted.plan.stateAfter.players.first.cash, 400);
    expect(accepted.plan.stateAfter.freeParkingPot, 129);
    expect(accepted.plan.safeResultSummary['amount'], 100);
    expect(accepted.plan.safeResultSummary['stateVersionAfter'], 2);
    expect(accepted.plan.safeResultSummary, isNot(contains('state')));
    expect(jsonEncode(accepted.publicResult), isNot(contains('seed')));
    expect(source.header.stateVersion, 1);
  });

  test('Free Parking collection and zero pot remain Engine-owned', () {
    final collected = evaluate(
      state: syntheticTaxFreeParkingState(position: 33, pot: 263),
    ) as AuthorityTaxFreeParkingAccepted;
    final empty = evaluate(
      state: syntheticTaxFreeParkingState(position: 33, pot: 0),
    ) as AuthorityTaxFreeParkingAccepted;

    expect(
      collected.plan.enginePlan.kind,
      LandingEconomyKind.freeParkingCollected,
    );
    expect(collected.plan.stateAfter.players.first.cash, 763);
    expect(collected.plan.stateAfter.freeParkingPot, 0);
    expect(empty.plan.enginePlan.amount, 0);
    expect(empty.plan.stateAfter.players.first.cash, 500);
  });

  test('insufficient tax delegates to the canonical DebtCase path', () {
    final accepted = evaluate(
      state: syntheticTaxFreeParkingState(cash: 99),
    ) as AuthorityTaxFreeParkingAccepted;

    expect(accepted.plan.enginePlan.kind, LandingEconomyKind.taxDebtOpened);
    expect(accepted.plan.stateAfter.players.first.cash, 99);
    expect(accepted.plan.stateAfter.freeParkingPot, 29);
    expect(
      accepted.plan.stateAfter.debtCase?['purpose'],
      'taxToFreeParkingPot',
    );
    expect(accepted.plan.stateAfter.pendingDecision?['kind'], 'debtResolution');
  });

  test('stale version and stale landing context have zero economic effect', () {
    final source = syntheticTaxFreeParkingState(position: 33, pot: 263);
    final staleVersion = evaluate(
      state: source,
      expectedStateVersion: 0,
    ) as AuthorityTaxFreeParkingRejected;
    final staleLanding = evaluate(
      state: source,
      expectedLandingIndex: 31,
    ) as AuthorityTaxFreeParkingRejected;

    expect(
      staleVersion.rejection.errorCode,
      TaxFreeParkingErrorCode.staleVersion,
    );
    expect(
      staleLanding.rejection.errorCode,
      TaxFreeParkingErrorCode.invalidState,
    );
    expect(source.players.first.cash, 500);
    expect(source.freeParkingPot, 263);
    expect(source.header.stateVersion, 1);
  });

  test('semantic fingerprint covers every result-affecting captured input', () {
    String fingerprint({DateTime? at, int landing = 31}) =>
        AuthorityTaxFreeParkingPlanner.inputHash(
          gameId: 'game-us019',
          expectedStateVersion: 1,
          playerId: 'p1',
          expectedLandingIndex: landing,
          transitionTime: at ?? syntheticTaxFreeParkingTime,
        );

    expect(fingerprint(), hasLength(64));
    expect(fingerprint(), fingerprint());
    expect(fingerprint(landing: 33), isNot(fingerprint()));
    expect(
      fingerprint(
        at: syntheticTaxFreeParkingTime.add(const Duration(seconds: 1)),
      ),
      isNot(fingerprint()),
    );
  });

  test('shared Emulator fixture is generated by canonical Authority plans', () {
    final fixture = jsonDecode(
      File('test/fixtures/tax_free_parking_plans.json').readAsStringSync(),
    );
    expect(fixture, syntheticTaxFreeParkingFixtureJson());
  });
}
